apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-ranzcr-nccl"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: gcr.io/arrikto-playground/dimpo/ranzcr-dist:latest 
              args: ["--epochs", "3", "--batch-size", "512", "--weight-decay", "0.1", "--image-size", "224", "--backend", "nccl"]
    Worker:
      replicas: 1 
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: gcr.io/arrikto-playground/dimpo/ranzcr-dist:latest
              args: ["--epochs", "3", "--batch-size", "512", "--weight-decay", "0.1", "--image-size", "224", "--backend", "nccl"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
